language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

after_success:
  - mvn -pl java-wrapper deploy --settings .travis-settings.xml -DskipTests=true -B

env:
  global:
  - secure: S4wrefbG2JvPcOeWsQZonn1D15zdCGj6FxBX/QkoVE6tAbzJb943G44Wd9Pwdfam7X5Q5up4ulPSDFPD7hcAPHsWpJmRDnzgzVqDyxomcOhkyFpZnBZpBKrzoVCTQX814XYpUfXo6939WuEeH9cDNy1q0frt5tke9r8RrOHXDokYA5PlGu2SLkmKVaiqpqSTqXFoNB1Lf3MzsVCeZVdm39KtpYrI4Xq30xB9Xwa/HBJFL4M2bOD0xvTppuf7ACl0KxsSgyy0dbnMf8CKQyKRfdH7vjbyChho9Y88KhXyJ6sDMgNDAfuJ5QZmJEalVq/zC7LAibrKrTIsv+21z8ybWresKcL1v78xSy694Z2wG+cYePxJHACeLxwSH5jk9pdAtzDG27vijdwZ/SWSrr7YIv9Ri5xpCJaAX5YunaQp+8RtAIgIN5+sRZiC2VT+QfcdA/gM4q6a1yMx38NTQelzjub28wFUVmkhJyY4cjSqBCNw9YFLQMhZUfKfejlK9I8/rjUvFW9zHivTSMK6RYhDleUZo9sWKLiugk+/BCdEfj9jIuDsEv08Lhgwnq66rpR8n6foldNrwg4sIWr2a7ZEBaeuBuag5Bw/RqEvXEmBQRnTANxIJHkxM64bFGS/fFrd6pRgKw3dIMUjUDTAlTwFaH/q7IaReliwOz7WqYa7V/k=
  - secure: LP3JdsK3qy9qdh+pI+us0GO4LGG1r9aDuuOmIwlDVNVfT38KLn9dSSLZgUkC554b8ztgg017f9+P3CBQGLKJbMUDIzCLnfqEpNrzxAWNq55mMVUY4wxA44XgEPdNBYSba0WzMzViBKyZDaJvVRxirXTWuNwQ0w8SLCsAGmP14spYMBq2+1jrqOGUJuDXvZ07IBhMjBWB0cCm6CkypAvTGaoh/OSgBQgzSMPClxRNwJCxw4hOz8oEsPSvci9mK8g5GM5lvjIAMg9CsDpcaSOQQ7Jq7/Drg188Sp7z0WnNufJxtub/yy+KlvqEVk44ECyVpGZgzs/szT98T1mtK27gYpd3Ijca7FFxiyT/W9oDLw9shTe1ZszrnIg4O25afj6zuKLN5huEmUio+cbVXzVUDdyDgbaAfArVsTVS9SwhtdDApwktMYnLv4+6CtyYaoER/3HVYHwZCn2haPrX30uNwA1943njoxfHO/wT1Zyz73WhwY9epIW40pSYUPm/fmjtHC0WDgrdnx9Iko2vTZaeGM+7fBmyMLQWE/W0b5JnZIwWteJrPjPvFx7at/1v4A2i5ZY+K3GX/jzkfD70MibeqZn6U8CRhq0eRHUqJVV5fqpztFzVCoY1MaIOrR2EY32uiUj0/+vX/pNQR+ItQhHkNFsyfDpuTDHBu7YH20+rOgg=
